version: "2"
services:
  node:
    image: mhart/alpine-node:10
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app

  test:
    extends:
      service: node
    command: npm run test
    environment:
      - PORT=3000

  dev:
    extends:
      service: node
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - PORT=3000
    labels:
      - "traefik.backend=dev"
      - "traefik.frontend.rule=PathPrefixStrip:/dev"
      - "traefik.port=80"
